/*
 * This file is generated by jOOQ.
 */
package com.nullXer0.dbee.enums;


import com.nullXer0.dbee.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum Component implements EnumType {

    BUTTON("BUTTON"),

    SELECT("SELECT"),

    TEXT("TEXT"),

    USER("USER"),

    ROLE("ROLE"),

    MENTION("MENTION"),

    CHANNEL("CHANNEL");

    private final String literal;

    private Component(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "Component";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static Component lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Component.class, literal);
    }
}
