/*
 * This file is generated by jOOQ.
 */
package com.nullXer0.dbee.enums;


import com.nullXer0.dbee.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum TeamRole implements EnumType {

    CAPTAIN("CAPTAIN"),

    CO_CAPTAIN("CO_CAPTAIN"),

    COACH("COACH");

    private final String literal;

    private TeamRole(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "team_role";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static TeamRole lookupLiteral(String literal) {
        return EnumType.lookupLiteral(TeamRole.class, literal);
    }
}
