/*
 * This file is generated by jOOQ.
 */
package com.nullXer0.dbee;


import com.nullXer0.dbee.tables.DiscordRoles;
import com.nullXer0.dbee.tables.TeamMembers;
import com.nullXer0.dbee.tables.TeamRoles;
import com.nullXer0.dbee.tables.Teams;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.discord_roles</code>.
     */
    public final DiscordRoles DISCORD_ROLES = DiscordRoles.DISCORD_ROLES;

    /**
     * The table <code>public.team_members</code>.
     */
    public final TeamMembers TEAM_MEMBERS = TeamMembers.TEAM_MEMBERS;

    /**
     * The table <code>public.team_roles</code>.
     */
    public final TeamRoles TEAM_ROLES = TeamRoles.TEAM_ROLES;

    /**
     * The table <code>public.teams</code>.
     */
    public final Teams TEAMS = Teams.TEAMS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DiscordRoles.DISCORD_ROLES,
            TeamMembers.TEAM_MEMBERS,
            TeamRoles.TEAM_ROLES,
            Teams.TEAMS
        );
    }
}
