/*
 * This file is generated by jOOQ.
 */
package com.nullXer0.dbee;


import com.nullXer0.dbee.tables.DiscordRoles;
import com.nullXer0.dbee.tables.TeamMembers;
import com.nullXer0.dbee.tables.TeamRoles;
import com.nullXer0.dbee.tables.Teams;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.discord_roles</code>.
     */
    public static final DiscordRoles DISCORD_ROLES = DiscordRoles.DISCORD_ROLES;

    /**
     * The table <code>public.team_members</code>.
     */
    public static final TeamMembers TEAM_MEMBERS = TeamMembers.TEAM_MEMBERS;

    /**
     * The table <code>public.team_roles</code>.
     */
    public static final TeamRoles TEAM_ROLES = TeamRoles.TEAM_ROLES;

    /**
     * The table <code>public.teams</code>.
     */
    public static final Teams TEAMS = Teams.TEAMS;
}
