/*
 * This file is generated by jOOQ.
 */
package com.nullXer0.dbee.tables.records;


import com.nullXer0.dbee.tables.Teams;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamsRecord extends UpdatableRecordImpl<TeamsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.teams.team_id</code>.
     */
    public void setTeamId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.teams.team_id</code>.
     */
    public Integer getTeamId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.teams.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.teams.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamsRecord
     */
    public TeamsRecord() {
        super(Teams.TEAMS);
    }

    /**
     * Create a detached, initialised TeamsRecord
     */
    public TeamsRecord(Integer teamId, String name) {
        super(Teams.TEAMS);

        setTeamId(teamId);
        setName(name);
        resetTouchedOnNotNull();
    }
}
