/*
 * This file is generated by jOOQ.
 */
package com.nullXer0.dbee.tables.records;


import com.nullXer0.dbee.tables.TeamRoles;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamRolesRecord extends UpdatableRecordImpl<TeamRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.team_roles.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.team_roles.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.team_roles.role</code>.
     */
    public void setRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.team_roles.role</code>.
     */
    public String getRole() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamRolesRecord
     */
    public TeamRolesRecord() {
        super(TeamRoles.TEAM_ROLES);
    }

    /**
     * Create a detached, initialised TeamRolesRecord
     */
    public TeamRolesRecord(Integer roleId, String role) {
        super(TeamRoles.TEAM_ROLES);

        setRoleId(roleId);
        setRole(role);
        resetTouchedOnNotNull();
    }
}
