/*
 * This file is generated by jOOQ.
 */
package com.nullXer0.dbee.tables.records;


import com.nullXer0.dbee.enums.TeamRole;
import com.nullXer0.dbee.tables.TeamMembers;

import java.time.OffsetDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamMembersRecord extends TableRecordImpl<TeamMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.team_members.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.team_members.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.team_members.team_id</code>.
     */
    public void setTeamId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.team_members.team_id</code>.
     */
    public Integer getTeamId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.team_members.team_role</code>.
     */
    public void setTeamRole(TeamRole value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.team_members.team_role</code>.
     */
    public TeamRole getTeamRole() {
        return (TeamRole) get(2);
    }

    /**
     * Setter for <code>public.team_members.date_joined</code>.
     */
    public void setDateJoined(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.team_members.date_joined</code>.
     */
    public OffsetDateTime getDateJoined() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.team_members.date_left</code>.
     */
    public void setDateLeft(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.team_members.date_left</code>.
     */
    public OffsetDateTime getDateLeft() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamMembersRecord
     */
    public TeamMembersRecord() {
        super(TeamMembers.TEAM_MEMBERS);
    }

    /**
     * Create a detached, initialised TeamMembersRecord
     */
    public TeamMembersRecord(Integer id, Integer teamId, TeamRole teamRole, OffsetDateTime dateJoined, OffsetDateTime dateLeft) {
        super(TeamMembers.TEAM_MEMBERS);

        setId(id);
        setTeamId(teamId);
        setTeamRole(teamRole);
        setDateJoined(dateJoined);
        setDateLeft(dateLeft);
        resetTouchedOnNotNull();
    }
}
